# Generated by Django 6.0.6 on 2026-06-21 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('member', '0016_alter_memberhistory_member_and_more'),
        ('member_financial_management', '0009_alter_invoiceitem_restaurant_items'),
        ('restaurant', '0002_spicylevel_restaurantinventoryitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossOrderingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_type', models.CharField(help_text='bar / tea_lounge / cigar_lounge', max_length=20)),
                ('target_type', models.CharField(help_text='bar / tea_lounge / cigar_lounge / restaurant', max_length=20)),
                ('allowed', models.BooleanField(default=True)),
                ('requires_room_number', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('source_type', 'target_type')},
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('outlet_type', models.CharField(choices=[('bar', 'bar'), ('tea_lounge', 'tea_lounge'), ('cigar_lounge', 'cigar_lounge')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=14)),
                ('capacity', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=6)),
                ('opening_time', models.TimeField(blank=True, default=None, null=True)),
                ('closing_time', models.TimeField(blank=True, default=None, null=True)),
                ('admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_outlets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutletInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=300)),
                ('unit', models.CharField(max_length=50)),
                ('current_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='outlet.outlet')),
            ],
            options={
                'unique_together': {('name', 'outlet')},
            },
        ),
        migrations.CreateModel(
            name='OutletItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=300)),
                ('outlet_type', models.CharField(blank=True, choices=[('bar', 'bar'), ('tea_lounge', 'tea_lounge'), ('cigar_lounge', 'cigar_lounge')], default='', max_length=20)),
            ],
            options={
                'unique_together': {('name', 'outlet_type')},
            },
        ),
        migrations.CreateModel(
            name='OutletItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('spicy_selectable', models.BooleanField(default=False)),
                ('is_public_show', models.BooleanField(default=False)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='outlet.outlet')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='outlet.outletitemcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutletItemMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='outlet/items/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='outlet.outletitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutletOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_number', models.CharField(db_index=True, max_length=60, unique=True)),
                ('status', models.CharField(choices=[('pending_otp', 'pending_otp'), ('confirmed', 'confirmed'), ('preparing', 'preparing'), ('ready', 'ready'), ('served', 'served'), ('billed', 'billed'), ('cancelled', 'cancelled')], db_index=True, default='pending_otp', max_length=20)),
                ('placed_by', models.CharField(choices=[('member', 'member'), ('waiter', 'waiter')], default='member', max_length=15)),
                ('room_number', models.CharField(blank=True, default='', max_length=30)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField(blank=True, default='')),
                ('otp_code', models.CharField(blank=True, default='', max_length=6)),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp_sent_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('guest', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlet_orders', to='attendance.guest')),
                ('invoice', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlet_orders', to='member_financial_management.invoice')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outlet_orders', to='member.member')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='outlet.outlet')),
                ('waiter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiter_outlet_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutletInventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('movement', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlet_inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='outlet.outletinventoryitem')),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='outlet.outletorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutletOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('source_type', models.CharField(blank=True, default='', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outlet.outletorder')),
                ('outlet_item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='outlet.outletitem')),
                ('restaurant_item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outlet_order_items', to='restaurant.restaurantitem')),
                ('spicy_level', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlet_order_items', to='restaurant.spicylevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutletItemRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity_per_unit', models.DecimalField(decimal_places=3, max_digits=12)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='outlet.outletinventoryitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_lines', to='outlet.outletitem')),
            ],
            options={
                'unique_together': {('item', 'inventory_item')},
            },
        ),
    ]
