# Generated by Django 6.0.6 on 2026-06-21 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('member', '0016_alter_memberhistory_member_and_more'),
        ('member_financial_management', '0009_alter_invoiceitem_restaurant_items'),
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpicyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rank', models.PositiveSmallIntegerField(default=0, help_text='Lower = milder, used for ordering in UI')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=300)),
                ('unit', models.CharField(help_text='e.g. kg, ltr, pcs', max_length=50)),
                ('current_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0, help_text='Alert when stock falls to/below this', max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='restaurant.restaurant')),
            ],
            options={
                'unique_together': {('name', 'restaurant')},
            },
        ),
        migrations.CreateModel(
            name='RestaurantItemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('spicy_selectable', models.BooleanField(default=False, help_text='If False, members cannot pick a spicy level for this item')),
                ('is_public_show', models.BooleanField(default=False, help_text="If True, appears on the public 'show' menu the admin posts")),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to='restaurant.restaurantitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_number', models.CharField(db_index=True, max_length=60, unique=True)),
                ('status', models.CharField(choices=[('pending_otp', 'pending_otp'), ('confirmed', 'confirmed'), ('preparing', 'preparing'), ('ready', 'ready'), ('served', 'served'), ('billed', 'billed'), ('cancelled', 'cancelled')], db_index=True, default='pending_otp', max_length=20)),
                ('serve_location', models.CharField(choices=[('room', 'room'), ('restaurant', 'restaurant')], default='restaurant', max_length=15)),
                ('room_number', models.CharField(blank=True, default='', max_length=30)),
                ('placed_by', models.CharField(choices=[('member', 'member'), ('waiter', 'waiter')], default='member', max_length=15)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField(blank=True, default='')),
                ('otp_code', models.CharField(blank=True, default='', max_length=6)),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp_sent_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('guest', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_orders', to='attendance.guest')),
                ('invoice', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_orders', to='member_financial_management.invoice')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_orders', to='member.member')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='restaurant.restaurant')),
                ('waiter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiter_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantInventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('movement', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='restaurant.restaurantinventoryitem')),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='restaurant.restaurantorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='restaurant.restaurantitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.restaurantorder')),
                ('spicy_level', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='restaurant.spicylevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantItemRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity_per_unit', models.DecimalField(decimal_places=3, help_text='Inventory consumed per 1 unit of the menu item', max_digits=12)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='restaurant.restaurantinventoryitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_lines', to='restaurant.restaurantitem')),
            ],
            options={
                'unique_together': {('item', 'inventory_item')},
            },
        ),
    ]
