# Generated by Django 5.1.5 on 2026-07-07 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0017_member_user"),
        ("restaurant", "0002_spicylevel_restaurantinventoryitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="about_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="banner_bg_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="restaurant/banners/"
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="banner_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="banner_title",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="delivery_banner_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="delivery_banner_title",
            field=models.CharField(default="30 Minutes Delivery!", max_length=200),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="meta_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="meta_title",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="reservation_banner_dinner_menu",
            field=models.CharField(default="50+ items", max_length=100),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="reservation_banner_launch_menu",
            field=models.CharField(default="30+ items", max_length=100),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="reservation_banner_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="reservation_banner_title",
            field=models.CharField(
                default="Reservation Your Favorite Private Table", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="slug",
            field=models.SlugField(blank=True, max_length=350, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="restaurantitem",
            name="additional_info",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="restaurantitem",
            name="free_bonus",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="restaurantitem",
            name="half_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="restaurantitem",
            name="sku",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="restaurantitem",
            name="slug",
            field=models.SlugField(blank=True, max_length=350, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="restaurantitem",
            name="stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="restaurantitem",
            name="sub_items",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="restaurantitem",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="RestaurantItemReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("review_text", models.TextField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="restaurant.restaurantitem",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="restaurant_item_reviews",
                        to="member.member",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RestaurantMenuSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=300)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="restaurant/sections/"
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_sections",
                        to="restaurant.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("restaurant", "title")},
            },
        ),
        migrations.AddField(
            model_name="restaurantitem",
            name="menu_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="restaurant.restaurantmenusection",
            ),
        ),
        migrations.CreateModel(
            name="RestaurantTestimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=300)),
                (
                    "designation",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("title", models.CharField(blank=True, default="", max_length=300)),
                ("text", models.TextField()),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="restaurant.restaurant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
