# Generated by Django 5.1.5 on 2026-07-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant",
            "0003_restaurant_about_text_restaurant_banner_bg_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantitem",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="restaurant/items/covers/"
            ),
        ),
    ]
