# Generated by Django 5.1.5 on 2026-07-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_restaurantitem_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="footer_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="restaurantmenusection",
            name="layout_type",
            field=models.CharField(
                choices=[
                    ("default", "Default/Tabs"),
                    ("left", "Left Column"),
                    ("right", "Right Column"),
                ],
                default="default",
                max_length=50,
            ),
        ),
    ]
