# Generated by Django 5.1.5 on 2026-07-08 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0017_member_user"),
        ("restaurant", "0005_restaurant_footer_config_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantitemreview",
            name="reviewer_name",
            field=models.CharField(blank=True, default="Admin", max_length=200),
        ),
        migrations.AlterField(
            model_name="restaurantitemreview",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="restaurant_item_reviews",
                to="member.member",
            ),
        ),
    ]
