# Generated by Django 5.1.5 on 2026-07-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0006_review_nullable_member_reviewer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantitemreview",
            name="reviewer_avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="restaurant/reviews/"
            ),
        ),
    ]
