# Generated by Django 5.0.6 on 2026-09-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0007_review_reviewer_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="dp_image",
            field=models.ImageField(blank=True, null=True, upload_to="restaurant/dp/"),
        ),
    ]
