# Generated by Django 6.0.6 on 2026-06-21 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0016_alter_memberhistory_member_and_more'),
        ('member_financial_management', '0009_alter_invoiceitem_restaurant_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservableResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('resource_type', models.CharField(choices=[('card_room', 'card_room'), ('pool', 'pool'), ('badminton', 'badminton'), ('paddle', 'paddle')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, help_text='Advance payment required to confirm a reservation', max_digits=10)),
                ('capacity', models.PositiveIntegerField(default=1, help_text='Max concurrent reservations for this resource')),
                ('max_per_member', models.PositiveIntegerField(default=1, help_text='Highest number of simultaneous bookings per member')),
                ('slot_minutes', models.PositiveIntegerField(default=60)),
                ('opening_time', models.TimeField(blank=True, default=None, null=True)),
                ('closing_time', models.TimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('maintenance', 'maintenance')], default='open', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reservation_number', models.CharField(db_index=True, max_length=60, unique=True)),
                ('status', models.CharField(choices=[('pending_payment', 'pending_payment'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled'), ('completed', 'completed')], db_index=True, default='pending_payment', max_length=20)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('party_size', models.PositiveIntegerField(default=1)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_paid', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='member_financial_management.invoice')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='member.member')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservation.reservableresource')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
