# Generated by Django 6.0.6 on 2026-06-21 12:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0016_alter_memberhistory_member_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staff_ID', models.CharField(db_index=True, max_length=100, unique=True)),
                ('designation', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('guest_allowed', models.BooleanField(default=False, help_text='Admin toggle: can this staff member register guests?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('card_uid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('card_type', models.CharField(choices=[('member', 'member'), ('staff', 'staff'), ('guest_temporary', 'guest_temporary')], max_length=20)),
                ('is_assigned', models.BooleanField(default=False)),
                ('member', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_cards', to='member.member')),
                ('staff', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_cards', to='attendance.staffprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('guest_relation', models.CharField(choices=[('guest', 'guest'), ('family', 'family')], default='guest', help_text='Distinguishes an outside guest from a family member', max_length=10)),
                ('host_type', models.CharField(choices=[('member', 'member'), ('staff', 'staff')], default='member', max_length=10)),
                ('host_member', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guests', to='member.member')),
                ('temporary_card', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_assignments', to='attendance.rfidcard')),
                ('host_staff', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guests', to='attendance.staffprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subject_type', models.CharField(choices=[('member', 'member'), ('staff', 'staff'), ('guest', 'guest')], db_index=True, max_length=10)),
                ('check_in', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('check_out', models.DateTimeField(blank=True, default=None, null=True)),
                ('member', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='member.member')),
                ('guest', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='attendance.guest')),
                ('card', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='attendance.rfidcard')),
                ('staff', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='attendance.staffprofile')),
            ],
            options={
                'ordering': ['-check_in'],
            },
        ),
    ]
